# Render service definitions for Iris Plumber API

# API web em Docker usando SQLite
services:
  - type: web
    name: iris-plumber          # nome do serviço
    env: docker                 # ambiente Docker
    region: oregon              # escolha a região (ex: oregon, ireland...)
    branch: main                # branch do GitHub que dispara o deploy
    plan: free                  # plano gratuito
    dockerfilePath: Dockerfile  # caminho do Dockerfile no repositório
    healthCheckPath: "/health" # endpoint para health checks
    envVars:                    # variáveis de ambiente
      - key: JWT_SECRET
        value: JWT_PLACEHOLDER      
      - key: DB_URL
        value: "/app/predictions.db"  # caminho absoluto para o SQLite
      - key: PORT
        value: "10000"              # opcional, só para tornar explícito